[config]
mode = "dark"
type = "scheme_tonal_spot"
restart_apps = false

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/matugen.conf"
post_hook = "kitty @ set-colors --all ~/.config/kitty/matugen.conf || true"

[templates.fuzzel]
input_path = "~/.config/matugen/templates/fuzzel.ini"
output_path = "~/.config/fuzzel/fuzzel.ini"

[templates.mako]
input_path = "~/.config/matugen/templates/mako.conf"
output_path = "~/.config/mako/config"
post_hook = "makoctl reload || true"

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk4.css"
output_path = "~/.config/gtk-4.0/matugen.css"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk3.css"
output_path = "~/.config/gtk-3.0/matugen.css"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/matugen-wall.conf"

[templates.btop]
input_path = "~/.config/matugen/templates/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"
post_hook = "sed -i 's|^color_theme.*|color_theme = \"matugen\"|' ~/.config/btop/btop.conf"

[templates.cava]
input_path = "~/.config/matugen/templates/cava.conf"
output_path = "~/.config/cava/config"
