source = ~/.config/hypr/matugen-wall.conf

general {
    hide_cursor = true
}

background {
    monitor =
    path = $wallpaper
}

label {
    monitor =
    text = Locked
    text_align = center
    color = $color_text
    font_size = 24
    font_family = Inter
    position = 0, 200
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 45
    outline_thickness = 2
    dots_center = true
    fade_on_empty = false
    placeholder_text = Passwd...
    font_color = $color_text
    outer_color = $color_accent
    inner_color = $color_field
    check_color = $color_accent
    fail_color = $color_alert
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = $color_text
    font_size = 90
    font_family = Inter
    position = 0, -120
    halign = center
    valign = center
}
